environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - ARCHITECTURE: "x64"
      PYTHON_VERSION: "3.7"
      PYTHON: "C:\\Python37-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "python -m pip install --upgrade pip"
  # - "python -m pip install --upgrade setuptools"
  # - "python -m pip install --upgrade cython"
  - "python -m pip install -r test_requirements.txt"

build_script:
  - "python setup.py build"

test_script:
  # - "%CMD_IN_ENV% python -m unittest discover"
  - "python -m coverage run --branch --source . -m unittest discover --verbose"
  # - "%CMD_IN_ENV% python -m coverage run --source . setup.py test"

after_test:
  # - "python setup.py bdist_wheel"
  # - "%CMD_IN_ENV% python setup.py bdist_wininst"
  # - "%CMD_IN_ENV% python setup.py bdist_msi"
  - ps: "ls"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/25b43ed5bc5e1d3a0772
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
